// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLX75buf6xP0xtuM0NMZ0ss5f3clu1oPg',
    appId: '1:896582959318:web:408104405beeb81113c977',
    messagingSenderId: '896582959318',
    projectId: 'chat-app-4f0cb',
    authDomain: 'chat-app-4f0cb.firebaseapp.com',
    storageBucket: 'chat-app-4f0cb.appspot.com',
    measurementId: 'G-Y3RE2WTLR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXEEOmykE3_XidA_8j-y8m5n3CEoyopQ',
    appId: '1:896582959318:android:ee361183c25cca3d13c977',
    messagingSenderId: '896582959318',
    projectId: 'chat-app-4f0cb',
    storageBucket: 'chat-app-4f0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxdLLB9Gx9QxVRvCB-W4W6Shsxa25cLc',
    appId: '1:896582959318:ios:e50f6272fb2ee60213c977',
    messagingSenderId: '896582959318',
    projectId: 'chat-app-4f0cb',
    storageBucket: 'chat-app-4f0cb.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxdLLB9Gx9QxVRvCB-W4W6Shsxa25cLc',
    appId: '1:896582959318:ios:e50f6272fb2ee60213c977',
    messagingSenderId: '896582959318',
    projectId: 'chat-app-4f0cb',
    storageBucket: 'chat-app-4f0cb.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLX75buf6xP0xtuM0NMZ0ss5f3clu1oPg',
    appId: '1:896582959318:web:0ee5661e7133148b13c977',
    messagingSenderId: '896582959318',
    projectId: 'chat-app-4f0cb',
    authDomain: 'chat-app-4f0cb.firebaseapp.com',
    storageBucket: 'chat-app-4f0cb.appspot.com',
    measurementId: 'G-TJNQJZ13L7',
  );
}
